version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.62.1
        environment:
          # Fail the build if there are warnings
          RUSTFLAGS: '-D warnings'
          SQLX_VERSION: 0.5.7
          SQLX_FEATURES: postgres
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: newsletter
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Install sqlx-cli
          command: cargo install --version=$SQLX_VERSION sqlx-cli --no-default-features --features $SQLX_FEATURES
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Install dependency auditing tool
          command: cargo install cargo-audit
      - run:
          name: Migrate DB
          command: |
            SKIP_DOCKER=true ./scripts/init_db.sh
      - run:
          name: Formatting
          command: cargo fmt --all -- --check
      - run:
          name: Linting
          command: cargo clippy -- -D warnings
      - run:
          name: Build all targets
          command: cargo build
      - run:
          name: Run all tests
          command: cargo test
      - run:
          name: Check for known security issues in dependencies
          command: cargo audit

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
